pipeline:
  # restore-cache:
  #   image: plugins/s3-cache:1
  #   pull: true
  #   restore: true
  #   secrets: [ aws_access_key_id, aws_secret_access_key ]
  #   root: publici-drone/
  #   mount:
  #     - ./.npm-cache
  #     - ./node_modules

  install-cli:
    image: node:8.12.0-alpine
    commands:
      - npm ci

  scaffold:
    image: node:8.12.0-alpine
    commands:
      - apk add expect
      - chmod +x scaffold.sh
      - ./scaffold.sh

  install-deps:
    image: node:8.12.0-alpine
    commands:
      - cd test
      - npm config set cache .npm-cache
      - npm ci --production

  generate:
    image: node:8.12.0-alpine
    commands:
      - cd test
      - npm run generate

  # rebuild-cache:
  #   image: plugins/s3-cache:1
  #   pull: true
  #   rebuild: true
  #   secrets: [ aws_access_key_id, aws_secret_access_key ]
  #   root: publici-drone/
  #   mount:
  #     - ./.npm-cache
  #     - ./node_modules
  #   when:
  #     branch: master

  # flush-cache:
  #   image: plugins/s3-cache:1
  #   pull: true
  #   secrets: [ aws_access_key_id, aws_secret_access_key ]
  #   root: publici-drone/
  #   flush: true

  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
      event: [push, tag, deployment]
