pipeline:
  # restore-cache:
  #   image: plugins/s3-cache:1
  #   pull: true
  #   restore: true
  #   secrets: [ aws_access_key_id, aws_secret_access_key ]
  #   root: publici-drone/
  #   mount:
  #     - ./.yarn-cache
  #     - ./node_modules

  install-cli:
    image: node:8.12.0-alpine
    commands:
      - yarn

  scaffold:
    image: node:8.12.0-alpine
    commands:
      - chmod +x scaffold.sh
      - ./scaffold.sh

  install-deps:
    image: node:8.12.0-alpine
    commands:
      - cd test
      - yarn config set cache-folder .yarn-cache
      - yarn install --pure-lockfile

  build:
    image: node:8.12.0-alpine
    commands:
      - yarn build

  # rebuild-cache:
  #   image: plugins/s3-cache:1
  #   pull: true
  #   rebuild: true
  #   secrets: [ aws_access_key_id, aws_secret_access_key ]
  #   root: publici-drone/
  #   mount:
  #     - ./.yarn-cache
  #     - ./node_modules
  #   when:
  #     branch: master

  # flush-cache:
  #   image: plugins/s3-cache:1
  #   pull: true
  #   secrets: [ aws_access_key_id, aws_secret_access_key ]
  #   root: publici-drone/
  #   flush: true

  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
