on: push
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set Node.js 14.x
      uses: actions/setup-node@master
      with:
        node-version: 14.x
    - name: install
      run: npm ci
    - name: test
      run: npm test
    - name: scaffold
      run: node index -y testing
    - name: generate
      working-directory: ./testing
      run: npm run generate
