on: push
name: Publish
jobs:
  publish:
    if: github.event.repository.name != 'nuxt-template'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set Node.js 14.x
      uses: actions/setup-node@master
      with:
        node-version: 14.x
    - name: install
      run: npm ci
    - name: generate
      run: npm run generate
    - name: push
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: npm run push
